#!/usr/bin/env python3
"""
evm_cov_merge.py — EVM Coverage Regression Merge Tool
======================================================
Reads per-run coverage CSV files produced by evm_coverage_db::write_log()
and computes merged (MAX across runs) coverage for each model.

Usage:
    python evm_cov_merge.py run1.evm_cov run2.evm_cov run3.evm_cov
    python evm_cov_merge.py *.evm_cov
    python evm_cov_merge.py *.evm_cov --threshold 90.0
    python evm_cov_merge.py *.evm_cov --output merged_report.txt

Input file format (generated by evm_coverage_db::write_log()):
    # EVM Coverage Log
    # testname,model_name,coverage_pct,target_pct,status
    basic_write_test,env.monitor.axi_cov,87.50,90.00,BELOW_TARGET
    random_write_test,env.monitor.axi_cov,94.30,90.00,PASS

Merge logic:
    - For each coverage model (by model_name), take the MAX percentage
      across all runs. This approximates bin-level coverage merge.
    - Note: True bin-level merge requires simulator-native tools
      (Questa vcover merge, VCS urg, Xcelium imc).
    - This script is a fast CI/CD gate — use simulator tools for signoff.

Exit codes:
    0 = all models meet their targets (or no targets defined)
    1 = one or more models below target
    2 = no coverage data found (empty files or no files given)
"""

import sys
import os
import glob
import argparse
from collections import defaultdict


def parse_args():
    parser = argparse.ArgumentParser(
        description='EVM Coverage Regression Merge Tool'
    )
    parser.add_argument(
        'files',
        nargs='+',
        help='.evm_cov files to merge (supports glob patterns)'
    )
    parser.add_argument(
        '--threshold', '-t',
        type=float,
        default=None,
        help='Override coverage threshold %% for ALL models (e.g., 90.0)'
    )
    parser.add_argument(
        '--output', '-o',
        type=str,
        default=None,
        help='Write merged report to a file in addition to stdout'
    )
    parser.add_argument(
        '--quiet', '-q',
        action='store_true',
        help='Only print PASS/FAIL summary, not per-model table'
    )
    return parser.parse_args()


def expand_files(file_patterns):
    """Expand glob patterns and return list of existing files."""
    files = []
    for pattern in file_patterns:
        expanded = glob.glob(pattern)
        if expanded:
            files.extend(expanded)
        elif os.path.exists(pattern):
            files.append(pattern)
    return sorted(set(files))


def read_coverage_file(filename):
    """
    Parse an evm_cov CSV file.
    Returns list of dicts: {testname, model, pct, target, status}
    """
    records = []
    try:
        with open(filename, 'r') as f:
            for line in f:
                line = line.strip()
                if not line or line.startswith('#'):
                    continue
                parts = line.split(',')
                if len(parts) < 5:
                    continue
                try:
                    records.append({
                        'testname': parts[0].strip(),
                        'model':    parts[1].strip(),
                        'pct':      float(parts[2].strip()),
                        'target':   float(parts[3].strip()),
                        'status':   parts[4].strip(),
                        'file':     filename,
                    })
                except ValueError:
                    continue
    except IOError as e:
        print(f'[evm_cov_merge] WARNING: Cannot read {filename}: {e}')
    return records


def merge_coverage(all_records, threshold_override=None):
    """
    Merge coverage across multiple runs.
    For each model: MAX(pct across all runs).
    Returns dict: model -> {max_pct, target, n_runs, runs}
    """
    models = defaultdict(lambda: {
        'max_pct':  0.0,
        'target':   0.0,
        'n_runs':   0,
        'runs':     [],  # list of (testname, pct)
    })

    for r in all_records:
        key = r['model']
        models[key]['max_pct'] = max(models[key]['max_pct'], r['pct'])
        if r['target'] > 0.0:
            models[key]['target'] = r['target']  # take last non-zero target
        models[key]['n_runs'] += 1
        models[key]['runs'].append((r['testname'], r['pct']))

    # Apply threshold override if given
    if threshold_override is not None:
        for key in models:
            models[key]['target'] = threshold_override

    return models


def format_report(models, files_processed, quiet=False):
    """Format the merged coverage report as a string."""
    lines = []
    lines.append('')
    lines.append('=' * 78)
    lines.append('         EVM COVERAGE REGRESSION MERGE REPORT')
    lines.append(f'         Files processed: {files_processed}')
    lines.append('=' * 78)

    if not quiet:
        lines.append(f'  {"Model":<44}  {"Max%":>7}  {"Target":>7}  {"Runs":>5}  Status')
        lines.append('  ' + '-' * 74)

    n_fail = 0
    n_pass = 0
    n_notarget = 0
    total_max = 0.0

    for model in sorted(models.keys()):
        data = models[model]
        max_pct = data['max_pct']
        target  = data['target']
        n_runs  = data['n_runs']
        total_max += max_pct

        if target > 0.0:
            if max_pct >= target:
                status = 'PASS'
                n_pass += 1
            else:
                status = f'FAIL (need {target:.1f}%)'
                n_fail += 1
        else:
            status = '---'
            n_notarget += 1

        if not quiet:
            if target > 0.0:
                lines.append(f'  {model:<44}  {max_pct:>6.1f}%  {target:>6.1f}%  {n_runs:>5}  {status}')
            else:
                lines.append(f'  {model:<44}  {max_pct:>6.1f}%    (none)  {n_runs:>5}  {status}')

    n_models = len(models)
    overall  = total_max / n_models if n_models > 0 else 0.0

    lines.append('  ' + '-' * 74)
    lines.append(f'  {"OVERALL (average, max per model)":<44}  {overall:>6.1f}%')
    lines.append('=' * 78)

    if n_fail == 0:
        if n_models == 0:
            verdict = 'NO COVERAGE DATA'
        elif n_notarget == n_models:
            verdict = f'PASS — {n_models} model(s) reported, no targets defined'
        else:
            verdict = f'PASS — {n_pass} model(s) met target(s)'
    else:
        verdict = f'FAIL — {n_fail} model(s) below target  ({n_pass} passed)'

    lines.append(f'  REGRESSION COVERAGE: {verdict}')
    lines.append('=' * 78)
    lines.append('')

    return '\n'.join(lines), n_fail, n_models


def main():
    args = parse_args()

    # Expand glob patterns
    files = expand_files(args.files)
    if not files:
        print('[evm_cov_merge] ERROR: No .evm_cov files found.')
        sys.exit(2)

    # Read all records
    all_records = []
    for f in files:
        records = read_coverage_file(f)
        all_records.extend(records)
        print(f'[evm_cov_merge] Loaded {len(records)} records from {f}')

    if not all_records:
        print('[evm_cov_merge] ERROR: No coverage data in any file.')
        sys.exit(2)

    # Merge
    models = merge_coverage(all_records, args.threshold)

    # Format report
    report, n_fail, n_models = format_report(models, len(files), args.quiet)

    # Print to stdout
    print(report)

    # Write to output file if requested
    if args.output:
        try:
            with open(args.output, 'w') as f:
                f.write(report)
            print(f'[evm_cov_merge] Report written to: {args.output}')
        except IOError as e:
            print(f'[evm_cov_merge] WARNING: Cannot write output file: {e}')

    # Exit code
    if n_models == 0:
        sys.exit(2)
    elif n_fail > 0:
        sys.exit(1)
    else:
        sys.exit(0)


if __name__ == '__main__':
    main()
